name: sup
description: Restaurant Finder App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^5.3.2+2
  flutter_svg: ^2.0.2
  intl: ^0.16.1
  flutter_config: ^2.0.0

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.4
  location: ^4.4.0
  fluttertoast: ^8.2.1
  http: ^0.13.5
  flutter_riverpod: ^2.3.0
  image_picker: ^0.8.7
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.0.18
  envied: ^0.3.0
  flutter_dotenv: ^5.0.2
  dio: ^5.0.2
  retrofit: '>=4.0.0 <5.0.0'
  logger: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  flutter_native_splash: ^2.2.19
  json_serializable: ^6.6.1
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
    - .env

  fonts:
    - family: JustMeAgainDownHere
      fonts:
        - asset: assets/fonts/JustMeAgainDownHere-Regular.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900


